
services:

  db:
    image: postgres:16
    container_name: postgres16
    environment:
      - POSTGRES_USER={{POSTGRES_USER}}
      - POSTGRES_PASSWORD=Eg.Te.De31
      - POSTGRES_DB=postgres
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo17:
    image: odoo:17
    container_name: odoo17
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=Eg.Te.De31
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      # - ./entrypoint.sh:/entrypoint.sh   # to install additional Python packages

    # automatically upgrade odoo custom addons
    command: >
      bash -c "odoo -u custom_project_extension" 
      

